# Generated by Django 2.1 on 2019-07-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.IntegerField()),
                ('director', models.CharField(max_length=15)),
                ('producer', models.CharField(max_length=15)),
                ('actor', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=15)),
            ],
        ),
    ]
