# Generated by Django 2.1 on 2019-07-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190707_1113'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='product',
            index_together=set(),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['actor'], name='blog_produc_actor_60025e_idx'),
        ),
    ]
